src/UI/LucasTechnology.Web/Models/ErrorViewModel.cs
using System;

namespace LucasTechnology.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/UI/LucasTechnology.Web/Controllers/About1Controller.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LucasTechnology.Web.Controllers
{
    public class About1Controller : Controller
    {
        // GET: AboutController
        public IActionResult Index()
        {
            return View();
        }

        
        
    }
}

src/UI/LucasTechnology.Web/Controllers/AboutController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LucasTechnology.Web.Controllers
{
    public class AboutController : Controller
    {
        // GET: AboutController
        public IActionResult Index()
        {
            return View();
        }

        
        
    }
}

src/UI/LucasTechnology.Web/Controllers/Account1Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace LucasTechnology.Web.Controllers
{
    public class Account1Controller : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/UI/LucasTechnology.Web/Controllers/HomeController.cs
using LucasTechnology.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace LucasTechnology.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/UI/LucasTechnology.Web/Controllers/ServiceController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LucasTechnology.Web.Controllers
{
    public class ServiceController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/UI/LucasTechnology.Web/Controllers/Services1Controller.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LucasTechnology.Web.Controllers
{
    public class Services1Controller : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/UI/LucasTechnology.Web/Views/About1/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>About Us</h1>

<style>

    p {
        color: white;
    }

    h1 {
        color: white;
    }

    
</style>

src/UI/LucasTechnology.Web/Views/Account1/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Account</h1>

<style>

    p {
        color: white;
    }

    h1 {
        color: white;
    }
</style>

src/UI/LucasTechnology.Web/Views/Consulting1/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

src/UI/LucasTechnology.Web/Views/Home/Index.cshtml
@{  

   ViewData["Title"] = "Home Page";
}
<style type="text/css">
    h1,
    p,
    h5 {
        color: white;
    }
</style>

<link rel="stylesheet" href="~/css/home.css">

<link rel="stylesheet" href="~/css/home.css">

@{
    ViewData["Title"] = "Home Page";
}
<style type="text/css">
    h1,
    p,
    h5 {
        color: white;
    }
</style>

<link rel="stylesheet" href="~/css/home.css">
<img src="~/media/Logomarca00100.png" height="480" length="120" align="centre"/> 

<div class="jumbotron-fluid imagebackground">
    
    
    
    <section class="h-100 w-100 justify-content-center">

         
               
        <div class="d-flex justify-content-center " style="height:60%">
            <div class="text-white mt-auto">

                <h1 id="middleText" class="mb-3"></h1>


            </div>
        </div>
        <div class="d-flex justify-content-center align-items-center " style="height:40%">
            <div class="text-white mb-auto">
                <a class="btn btn-outline-light btn-lg" href="/Services1#ref1" role="button">Create your web System with Us</a>
            </div>
        </div>


    </section>
</div>
<hr>
<section class="h-100">
    <table class="h-100">
        <h1 class="display-4 text-center " style="margin-bottom:10%">Our Services</h1>
        <br>
        <div class="row d-flex">
            <div class="align-bottom col-md-4 order-sm-1 order-2" data-aos="fade-up" data-aos-duration="1500"
                 data-aos-offset="500">
                <div class="card card-position" style="">
                    <div class="card-back-position"></div>
                    <img class="card-img-top" src="~/media/cloudinfrastructure.png" alt="Card image cap" style="border-radius: 50%;
                                    z-index: 2;">
                    <div class="card-body">
                        <h5 class="card-title text-center">Cloud Infrastructure</h5>
                        
                    </div>
                    <a href="/Services1#ref1" class="btn btn-secondary position-absolute-bottom" style="border-radius: 5px 5px 5px 5px;
                            width:100%;
                            box-shadow: 2px 2px 5px #000;">Learn More</a>
                </div>
            </div>

            <div class="align-middle col-md-4 order-sm-2 order-1" data-aos="fade-up" data-aos-duration="1500">

                <div class="card card-position" style="transform: translateY(-10px)">
                    <div class="card-back-position"></div>
                    <img class="card-img-top" src="~/media/solutionsinsoftware.png" alt="Card image cap" style="border-radius: 50%;
                                    z-index: 2;">
                    <div class="card-body">
                        <h5 class="card-title text-center">Software Development</h5>
                        <p class="card-text text-center ">Transforming ideas</p>

                    </div>
                    <a href="/About#ref2" class="btn btn-secondary position-absolute-bottom" style="border-radius: 5px 5px 5px 5px;
                            width:100%;
                            box-shadow: 2px 2px 5px #000;">Saiba Mais</a>
                </div>
            </div>

            <div class="align-bottom col-md-4 order-3" data-aos="fade-up" data-aos-duration="1500"
                 data-aos-offset="500">

                <div class="card card-position" style="">
                    <div class="card-back-position"></div>
                    <img class="card-img-top" src="~/media/projectconsulting.png" alt="Card image cap" style="border-radius: 50%;
                                    z-index: 2;">
                    <div class="card-body">
                        <h5 class="card-title text-center">Project Consulting</h5>
                        <p class="card-text text-center ">Planning your project to your success</p>
                    </div>
                    <a href="/#ref3" class="btn btn-secondary position-absolute-bottom" style="border-radius: 5px 5px 5px 5px;
                            width:100%;
                            box-shadow: 2px 2px 5px #000;">Saiba Mais</a>
                </div>
            </div>
    </table>
</section>

<script>
    let texts = ['A LIBERDADE DE CONVERSAR COM O MUNDO INTEIRO']
    consoleText(texts, 'middleText', ['white'])
    function consoleText(words, id, colors) {
        if (colors === undefined) colors = ['#fff'];
        var visible = true;
        var con = document.getElementById('console');
        var letterCount = 1;
        var x = 1;
        var waiting = false;
        var target = document.getElementById(id)
        target.setAttribute('style', 'color:' + colors[0])
        window.setInterval(function () {

            if (letterCount === 0 && waiting === false) {
                waiting = true;
                target.innerHTML = words[0].substring(0, letterCount)
                window.setTimeout(function () {
                    var usedColor = colors.shift();
                    colors.push(usedColor);
                    var usedWord = words.shift();
                    words.push(usedWord);
                    x = 1;
                    target.setAttribute('style', 'color:' + colors[0])
                    letterCount += x;
                    waiting = false;
                }, 1000)
            } else if (letterCount === words[0].length + 1 && waiting === false) {
                waiting = true;
                window.setTimeout(function () {
                    x = -1;
                    letterCount += x;
                    waiting = false;
                }, 1000)
            } else if (waiting === false) {
                target.innerHTML = words[0].substring(0, letterCount)
                letterCount += x;
            }
        }, 120)

    }
</script>

src/UI/LucasTechnology.Web/Views/Services1/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Services</h1>

<style>

    p {
        color: white;
    }

    h1 {
        color: white;
    }


</style>

src/UI/LucasTechnology.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Lucas Tecnologia Services</title>

    <!-- Primary Meta Tags -->
    <title>Lucas Tecnologia Services</title>
    <meta name="title" content="">
    <meta name="description" content="">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://lucastecnologiaservices.azurewebsites.net/">
    <meta property="og:title" content="Lucas Tecnologia Services">
    <meta property="og:description" content="">
    <meta property="og:image" coLucas Tecnologia Servicesntent="~/media/lais.jpg">

    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:url" content="https://lucastecnologiaservices.azurewebsites.net/">
    <meta property="twitter:title" content="Lucas Tecnologia Services">
    <meta property="twitter:description" content="">
    <meta property="twitter:image" content="~/media/Logomarca00100">

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
          integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet">
    <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>


</head>

<body style="margin-bottom:0" onload="loading()">


    <div id="loading-spinner" class="d-flex justify-content-center fixed-center h-100"
         style="background-color: white; height: 100vh">
        <div class="spinner-border" role="status">
            <span class="sr-only">Loading...</span>
        </div>
    </div>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 ">
            <div class="container d-flex">
                <a class="navbar-brand order-md-2 order-sm-1 row-sm-6 col-md-2  d-none d-sm-none d-md-block" asp-area=""
                   asp-controller="Home" asp-action="Index">
                    <img src="~/media/logoPlanB.png" width="200px" heigth="80px" alt="">
                </a>
                </button>
                <div class="row flex-nowrap justify-content-between w-100 d-sm-block d-md-none">
                    <a class="navbar-brand order-md-2 order-sm-1 row-sm-6 col-md-5 " asp-area="" asp-controller="Home"
                       asp-action="Index">
                        <img class="" src="~/media/logoPlanB.png" width="200px" heigth="80px" alt="">
                    </a>
                    <button class="navbar-toggler order-2 row-sm-6 border-0 " type="button" data-toggle="collapse"
                            data-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false"
                            aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between order-md-1 order-sm-2 col-md-4 ">
                    <ul class="navbar-nav flex-grow-1 ">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Services1"
                               asp-action="Index">Services</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Videos1"
                               asp-action="Index">Videos</a>
                        </li>

                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between order-md-3 col-md-5">
                    <ul class="navbar-nav flex-grow-1 ">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Course"
                               asp-action="Index">Cursos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Contact"
                               asp-action="Index">Contato</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="About" asp-action="Index">
                                Sobre
                                nós
                            </a>
                        </li>
                        <li class="nav-item studantButton">
                            <a href="/Account" class="btn btn-primary buttonStudent text-nowrap">
                                <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px"
                                     fill="#000000">
                                    <path d="M0 0h24v24H0z" fill="none" />
                                    <path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1.79 4 4 4zm0 2c-2.67 0-8 1.34-8 4v2h16v-2c0-2.66-5.33-4-8-4z" />
                                </svg> Área do Estudante
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3 h-100">
            @RenderBody()
        </main>
    </div>
    <br>
    <!-- Footer -->
    <footer class=" text-center text-white" style="background-color: #3e2558">
        <!-- Grid container -->
        <div class="container p-4 pb-0">
            <!-- Section: Social media -->
            <section class="mb-4">
                <!-- Facebook -->
                <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
                    <i class="fab fa-facebook-f"></i>
                </a>
                <!-- Instagram -->
                <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button">
                    <i class="fab fa-instagram"></i>
                </a>

            </section>
            <!-- Section: Social media -->
        </div>
        <!-- Grid container -->
        <!-- Grid container -->
        <div class="container p-0 pb-2">
            <!-- Section: Social media -->
            <section class="d-flex justify-content-center ">
                <a class="nav-link text-white" style="padding-right: .2em !important" asp-area="" asp-controller="Book"
                   asp-action="Index">Livros</a>
                <a class="nav-link text-white" style="padding-right: .2em !important" asp-area=""
                   asp-controller="AskQuest" asp-action="Index">Dúvidas</a>
                <a class="nav-link text-white" style="padding-right: .2em !important" asp-area=""
                   asp-controller="Course" asp-action="Index">Cursos</a>
                <a class="nav-link text-white" style="padding-right: .2em !important" asp-area="" asp-controller="Home"
                   asp-action="Contato">Contato</a>
                <a class="nav-link text-white" style="padding-right: .2em !important" asp-area="" asp-controller="About"
                   asp-action="Index">Sobre nós</a>

            </section>
            <!-- Section: Social media -->
        </div>
        <!-- Grid container -->
        <!-- Copyright -->
        <div class="text-center p-3 text-white" style="background-color: rgba(0, 0, 0, 0.2);">
            &copy; @DateTime.Now.Year - Plan B Idiomas
            <a class="" href="#">Plan B Idiomas</a>
        </div>
        <!-- Copyright -->
    </footer>
    <script>
        AOS.init();
        function loading() {
            $("#loading-spinner").removeClass("d-flex").addClass("d-none");
        }
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

src/UI/LucasTechnology.Web/Views/Video1/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Services</h1>

<style>

    p {
        color: white;
    }

    h1 {
        color: white;
    }
</style>